url: http://www.levihackwith.com
name: Levihackwith.com
title: LeviHackwith.com
post_images_folder: /images/posts
description: Ship Now. Iterate Later.
highlighter: 'rouge'
excerpt_separator: <!--more-->
sass:
    style: compressed
pagination: 20
permalink: /:slug
excerpt_separator: ""