url: http://www.levihackwith.com
name: Levihackwith.com
title: LeviHackwith.com
post_images_folder: /images/posts
description: Ship Now. Iterate Later.
highlighter: 'rouge'
kramdown:
    input: GFM
    hard_wrap: false

gems:
    - jekyll-gist

excerpt_separator: <!--more-->
sass:
    style: compressed
pagination: 20